pipeline:
  outputs:
    prod:
      type: bigquery
      method: service-account
      dataset: staging
      location: EU
      project: pipeline-374517
      keyfile: /Users/adammarples/.secrets/terraform@pipeline-374517.iam.gserviceaccount.com.json
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      threads: 4
  target: prod
