pipeline:
  outputs:
    dev:
      dataset: raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/adammarples/.secrets/orchestrator@pipeline-374517.iam.gserviceaccount.com.json
      location: EU
      method: service-account
      priority: interactive
      project: pipeline-374517
      threads: 4
      type: bigquery
  target: dev
