pipeline_profile:
  outputs:
    prod:
      type: bigquery
      method: service-account
      dataset: staging
      location: EU
      project: "{{ env_var('PROJECT') }}"
      keyfile: "{{ env_var('SECRETS') }}/orchestrator@{{ env_var('PROJECT') }}.iam.gserviceaccount.com.json"
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      threads: 4
  target: prod
