
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'pipeline_package'
version: '1.0.0'
require-dbt-version: '1.3.2'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'pipeline_profile'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  pipeline_package:
    stage:
      tags:
        - stage
      enabled: true
      materialized: view

    vault:
      tags:
        - vault
      materialized: incremental
      hubs:
        tags:
          - hubs
      links:
        tags:
          - links
      sats:
        tags:
          - sats
