# https://gaunacode.com/deploying-terraform-at-scale-with-github-actions
# https://github:com/hashicorp/setup-terraform:

name: 'Terraform - Prod'

on:
  push:
    branches:
    - main
    paths:
    - prod/**
  pull_request:
    branches:
    - main
    paths:
    - prod/**

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: prod
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
        terraform_wrapper: false
    - name: Terraform Init
      id: init
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }} # This doesn't have to be a secret. Client IDs are not sensitive.
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: "[Your Subscription ID]"
        ARM_TENANT_ID: "[Your Tenant ID]"
      working-directory: ./prod # Use your environment folder
      shell: bash